#!/usr/bin/env bash 

sudo useradd -r -s /bin/false grafana

wget https://dl.grafana.com/grafana/release/12.2.0/grafana_12.2.0_17949786146_linux_amd64.tar.gz
https://mirror.yandex.ru/mirrors/packages.grafana.com/oss/deb/pool/main/g/grafana/grafana_12.2.0_17949786146_linux_amd64.deb

tar -zxvf grafana-*.tar.gz

mv grafana-*/ /usr/local/bin/grafana

chown -R grafana:grafana /usr/local/bin/grafana/

nano /etc/systemd/system/grafana.service

[Unit]
Description=Grafana Server
After=network.target

[Service]
Type=simple
User=grafana
Group=grafana
ExecStart=/usr/local/bin/grafana/bin/grafana server --config=/usr/local/bin/grafana/conf/grafana.ini --homepath=/usr/local/bin/grafana
Restart=on-failure

[Install]
WantedBy=multi-user.target

cp -p /usr/local/bin/grafana/conf/defaults.ini /usr/local/bin/grafana/conf/grafana.ini

sudo systemctl daemon-reload
sudo systemctl enable --now grafana
sudo systemctl status grafana

пароль логин для доступа admin admin
добавление источника http://127.0.0.1:9090
нужно указывать и hhtp 
