#!/usr/bin/env bash 

sudo useradd -r -s /bin/false grafana

wget https://dl.grafana.com/oss/release/grafana-12.0.1.linux-amd64.tar.gz

tar -zxvf grafana-12.0.1.linux-amd64.tar.gz

mv grafana-v12.0.1/ /usr/local/bin/grafana

chown -R grafana:grafana /usr/local/bin/grafana/

nano /etc/systemd/system/grafana.service

[Unit]
Description=Grafana Server
After=network.target

[Service]
Type=simple
User=grafana
Group=grafana
ExecStart=/usr/local/bin/grafana/bin/grafana server --config=/usr/local/bin/grafana/conf/grafana.ini --homepath=/usr/local/bin/grafana
Restart=on-failure

[Install]
WantedBy=multi-user.target

cp -p /usr/local/bin/grafana/conf/defaults.ini /usr/local/bin/grafana/conf/grafana.ini

sudo systemctl daemon-reload
sudo systemctl enable --now grafana
sudo systemctl status grafana

пароль логин для доступа admin admin
